config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    #get "pages/home"
    root :to => "gyms#show"

  
  #get "gyms/show", to: "gyms#show"
  
  
  #get "new_user_session_path", to: "gyms#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tickets

  # resources :users
  
  resources :gyms
  
  resources :trudy_trends
  #root 'tickets#index'
  # namespace :charts do
  #   get "trends-by-day"
  # end
  # resources :charts, only: [] do
  #   collection do
  #     get 'trends_by_days'
  #   end
  # end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    belongs_to :gym
    
    validates :name, presence: true, format: { with: /\A[A-Z][a-z]+\s[A-Z][a-z]+\z/, message: "must include both first and last, separated by a space and properly capitalized" }
    
    @@queueTop = Ticket.where('floor = ?', 'top').order(:created_at).to_a
    @@queueBottom = Ticket.where('floor = ?', 'bottom').order(:created_at).to_a
    
    cattr_accessor :queueTop
    cattr_accessor :queueBottom
    
    def get_position_top
        if (User.current.admin)
            @@queueTop.index(self) + 1
        else
            @ticket = Ticket.find_by(user: User.current)
            @@queueTop.index(@ticket) + 1
        end
    end
    
    def get_position_bottom
        if (User.current.admin)
            @@queueBottom.index(self) + 1
        else
            @ticket = Ticket.find_by(user: User.current)
            @@queueBottom.index(@ticket) + 1
        end
    end


end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :user_signed_in?, only:[:new, :create]
    
    def index
        @ticketsTop = Ticket.where('floor = ?', 'top').order(:created_at).to_a
        @ticketsBottom = Ticket.where('floor = ?', 'bottom').order(:created_at).to_a
        @gym = Gym.find_by(name: "Trudy")
    end
    
    def new
        @ticket = Ticket.new
        @gym = Gym.find_by(name: "Trudy")
    end
  
    def create
        @ticket = Ticket.new(ticket_params)
        @ticket.user = current_user
        @ticket.gym = Gym.find_by(name: "Trudy")
        if @ticket.save
            flash[:notice] = "New ticket for #{@ticket.name} created for #{@ticket.floor} floor"
            increase_wait(@ticket)
            @ticket.floor == "top" ? (Ticket.queueTop << @ticket) : (Ticket.queueBottom << @ticket)
            redirect_to "/" and return
        else
            errmsg = @ticket.errors.full_messages.join(", ")
            flash[:alert] = "Error creating new ticket: #{errmsg}"
            redirect_to new_ticket_path and return
        end
    end
    

    def destroy
        @ticket = Ticket.find(params[:id])
        increase_occupancy(@ticket)
        decrease_wait(@ticket)
        @ticket.floor == "top" ? Ticket.queueTop.delete(@ticket) : Ticket.queueBottom.delete(@ticket)
        @ticket.destroy
        flash[:notice] = "#{@ticket.name} was admitted to the #{@ticket.floor} floor of the gym."
        redirect_to tickets_path and return
    end

    private
  
    def ticket_params
        params.require(:ticket).permit(:name, :floor)
    end
    
    def increase_wait(t)
        t.floor == "top" ? t.gym.add_wait_top_floor() : t.gym.add_wait_bottom_floor()
    end
    
    def decrease_wait(t)
        t.floor == "top" ? t.gym.subtract_wait_top_floor() : t.gym.subtract_wait_bottom_floor()
    end
    
    def increase_occupancy(t)
        t.floor == "top" ? t.gym.add_top_floor() : t.gym.add_bottom_floor()
    end
    
    def decrease_occupancy(t)
        t.floor == "top" ? t.gym.subtract_top_floor() : t.gym.subtract_bottom_floor()
    end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/index.html.erb
<div id="title">
  Admin Page
</div>
<br>
<h2><strong>Occupancy Values</strong></h2>
<br>
<table class = "center_table">
  <tr>
    <td class="occupancy">Current Top Floor Occupancy:  <strong class="num"><%= @gym.top_floor_occupancy %></strong></td>
    <td>
      
        <%= link_to("<button class='button' id='top_plus'>+</button>".html_safe, gym_path(:id => 3), method: :patch, class: 'plus_top') %>
      
    </td>
    <td>
        <%= link_to("<button class='button' id='top_minus'>-</button>".html_safe, gym_path(:id => 1), method: :patch, class: 'minus_top') %>
      
    </td>
  </tr>
  <tr>
    <td class="occupancy">Current Bottom Floor Occupancy:  <strong class="num"><%= @gym.bottom_floor_occupancy %></strong></td>
    <td>
        <%= link_to("<button class='button' id='bottom_plus'>+</button>".html_safe, gym_path(:id => 4), method: :patch, class: 'plus_bottom') %>
    </td>
    <td>
        <%= link_to("<button class='button' id='bottom_minus'>-</button>".html_safe, gym_path(:id => 2), method: :patch, class: 'minus_bottom') %>
    </td>
  </tr>
</table>
<br>
<br>
<br>
<div id="container">
  <div class="d-flex justify-content-center">
    <div class="title-button">
      <h2><strong>Top Floor Queue</strong></h2>
      <% unless Ticket.queueTop.empty? %>
        <button class="button" id="admit">
          <%= link_to("Admit to Top", @ticketsTop.first, method: :delete) %>
        </button>
      <% end %>
    </div>
    <div class="title-button">
       <h2><strong>Bottom Floor Queue</strong></h2>
    <% unless Ticket.queueBottom.empty? %>
      <button class="button" id="admit">
        <%= link_to("Admit to Bottom", @ticketsBottom.first, method: :delete) %>
      </button>
    <% end %>
  </div>
</div>

<div id = "container">
  <div class="d-flex justify-content-center">
    <table class="table" id="queue">
      <thead>
        <tr>
          <th>Position</th>
          <th>Name</th>
          <th>Email</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <% @ticketsTop.each do |t| %>
          <tr>
            <td class="position">
              <%= t.get_position_top %>
            </td>
            <td>
              <%= t.name %>
            </td>
            <td>
              <%= t.user.email %>
            </td>
            <td>
              <%= t.created_at.localtime("-05:00").strftime("at %I:%M %P") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <table class="table" id="queue">
      <thead class="thead">
        <tr>
          <th>Position</th>
          <th>Name</th>
          <th>Email</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <% @ticketsBottom.each do |t| %>
          <tr>
            <td class="position">
              <%= t.get_position_bottom %>
            </td>
            <td>
              <%= t.name %>
            </td>
            <td>
              <%= t.user.email %>
            </td>
            <td>
              <%= t.created_at.localtime("-05:00").strftime("at %I:%M %P") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tickets/new.html.erb
<% if @gym.check_tickets == false %>
    <div id="title">
        Submit a Ticket
    </div>
    <h4>
        To submit a ticket for the queue, please provide your <b>full name</b> and choose your desired <b>floor</b> from the dropdown menu.
    </h4>
    <h4>
        <i>Your email address (<%= current_user.email %>) will be recorded with your ticket.</i>
    </h4>
    <div id="container">
        <div id="create">  
            <%= form_with model: @ticket, local: true do |f| %>
                <div class="field">
                    <%= f.label :name, :class => "submit-ticket" %>
                    <%= f.text_field :name %>
                </div>
                <br >
                <div class="floor-field">
                    <%= f.label :floor, :class => "submit-ticket" %>
                    <%= f.select :floor, [['Top','top'],['Bottom','bottom']] %>
                </div>
                <br >
                <div>
                    <%= f.submit "Submit Ticket", :class => "button" %>
                </div>
            <% end %>
        </div>
    </div>
    <% else %>
    <div id="title">
        Ticket Already Submitted
    </div>
    <h2>
        <i>Looks like you are already waiting in the <%= current_user.ticket.floor %> floor queue!</i>
    </h2>
    <h2>
        <i>You are currently in position</i> <b><%= @gym.check_tickets %></b>.
    </h2>
<% end %>