config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    #get "pages/home"
    root :to => "gyms#show"

  
  #get "gyms/show", to: "gyms#show"
  
  
  #get "new_user_session_path", to: "gyms#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tickets

  # resources :users
  
  resources :gyms
  
  resources :trudy_trends
  #root 'tickets#index'
  # namespace :charts do
  #   get "trends-by-day"
  # end
  # resources :charts, only: [] do
  #   collection do
  #     get 'trends_by_days'
  #   end
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'shows', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'tickets' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-custom navbar-dark">
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav" >
          <li class="nav-item">
            <a class="nav-link" href="/">Home </a>
          </li>
          <li class="nav-item">

            <%= link_to "Trudy Trends", trudy_trends_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <% if user_signed_in? && current_user.admin %>
              <%= link_to "Admin Page", tickets_path, :class => "nav-link" %>
            <% end %>
          </li>
           <li class="nav-item">
              <% if user_signed_in? && current_user.admin == false%>
                <%= link_to "Get On Queue", new_ticket_path, :class => "nav-link" %>
              <% elsif user_signed_in? == false%>
                <%= link_to "Get On Queue", new_user_session_path, :class => "nav-link"%>
              <% end %>
          </li>
        </ul>
        <ul class="navbar-nav topnav-centered">
           <li class="nav-item">
              <%= link_to "Trudy Fitness Center", "/", :class => "nav-link" %>
            </li>
        </ul>
        <ul class = "navbar-nav ml-auto">
           <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "nav-link" %>
              <% else %>
                <%= link_to "Log In", new_user_session_path, :class => "nav-link" %>
              <% end %>
            </li>
        </ul>
      </div>  
    </nav>
    <% if flash[:notice] %>
      <div class="alert alert-primary"> 
        <%= "#{flash[:notice]}" %> 
      </div> 
    <% end %>
    
    <% if flash[:alert] %> 
      <div class="alert alert-warning">
        <%= "#{flash[:alert]}" %>
      </div> 
    <% end %>
    <%= yield %>
  </body>
</html>